#include <stdlib.h>
#include <vector>
#include <stdio.h>
#include <string>
#include <iostream>
#include <fstream>
#include <memory>

using std::make_unique;
using std::cin;
using std::cout;
using std::string;
using std::ifstream;
using std::ofstream;
using std::istream;
using std::ostream;
using std::ws;
using std::unique_ptr;
using std::vector;
#pragma once
